// <auto-generated /> 
#nullable enable

using JMESPath;

public class Current
{

    [Theory]
    [InlineData(
"""
@
""",
"""
{
  "foo": [
    {
      "name": "a"
    },
    {
      "name": "b"
    }
  ],
  "bar": {
    "baz": "qux"
  }
}
""")]
    [InlineData(
"""
@.bar
""",
"""
{
  "baz": "qux"
}
""")]
    [InlineData(
"""
@.foo[0]
""",
"""
{
  "name": "a"
}
""")]
    public void Test_1(string expression, string expectedResult)
    {
        // Arrange 
        string? given =
"""
{
  "foo": [
    {
      "name": "a"
    },
    {
      "name": "b"
    }
  ],
  "bar": {
    "baz": "qux"
  }
}
""";

        // Act 
        string? result = JMESPathSearcher.Search(expression, given);
        
        // Assert
        Assert.Equal(result, expectedResult);
    }

}